### ISSUE TITLE
What to do with the Contacts API?

### ISSUE THREAD

**Issue by filmaj** [phonegap/phonegap-plugin-pwa#24]
According to the [W3C Standards JS APIs list](https://www.w3.org/TR/#tr_Javascript_APIs), the current implementation of cordova-plugin-contacts looks to be based on the [Contacts Manager API](https://www.w3.org/TR/contacts-manager-api/). 

Under the JS APIs, this one is listed under the "obsolete" section.

This is also from the spec itself:

>  Members of this Working Group have agreed not to progress the Contacts Manager API specification further as a Recommendation track document, electing instead to publish it as an informative Working Group Note under a permissive license with a view to enabling it to form the basis of further work by others, e.g. in a W3C Community Group.

So no W3C work that I can see is out there tackling providing access to contacts data.

Do we still want to continue supporting this API per the "Working Group Note" the W3C / SysApps group _has_ worked on?

**Comment by stevengill** [comment]
Our users still need contact access. What would be an alternative?

**Comment by macdonst** [comment]
We do nothing. If our users need contact access they can continue to use the existing plugin or fork the plugin and work on it themselves.

**Comment by filmaj** [comment]
Well that solves that issue then!
